import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    // Will ignore the template or the default
    // absolute: "",

    // Will be displayed if the route don't have a title defined
    default: "Next.js tutorial - Codevolution", 

    // Create dynamic title adding a suffix or prefix
    template: "%s | Codevolution"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header><p>Header</p></header>

        {children}

        <footer><p>Footer</p></footer>
      </body>
    </html>
  )
}
