import { Metadata } from "next"
import "./style.css"

export const metadata: Metadata = {
  title: {
    // Will ignore the template or the default
    // absolute: "",

    // Will be displayed if the route don't have a title defined
    default: "Next.js tutorial - Codevolution", 

    // Create dynamic title adding a suffix or prefix
    template: "%s | Codevolution"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="w-full bg-slate-800 p-4 text-white"><p>Header</p></header>
        {children}
        <footer className="w-full bg-slate-800 p-4 text-white"><p>Footer</p></footer>
      </body>
    </html>
  )
}
